#!/usr/bin/env python3
"""Fast offline-ish EN catalog: hand map common UI + leave rest as source (ZH fallback OK)."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
zh = json.loads((ROOT / "lang" / "zh.json").read_text(encoding="utf-8"))

# High-frequency UI map (source-as-key → EN)
HAND = {
    "未找到": "Not found",
    "未登录": "Not signed in",
    "无权限": "Permission denied",
    "出错了": "Something went wrong",
    "服务器错误": "Server error",
    "服务器内部错误": "Internal server error",
    "参数错误": "Invalid parameters",
    "网络错误": "Network error",
    "登录": "Sign in",
    "退出登录": "Sign out",
    "PassPort 登录": "Sign in with PassPort",
    "我的组织": "My organizations",
    "我的任务": "My tasks",
    "用户设置": "User settings",
    "工作台": "Workspace",
    "新建组织": "New organization",
    "新建项目": "New project",
    "翻译工作台": "Translation editor",
    "源文件": "Source files",
    "导入": "Import",
    "导出": "Export",
    "设置": "Settings",
    "保存": "Save",
    "取消": "Cancel",
    "确定": "OK",
    "关闭": "Close",
    "删除": "Delete",
    "搜索": "Search",
    "添加": "Add",
    "移除": "Remove",
    "上传": "Upload",
    "下载": "Download",
    "刷新列表": "Refresh list",
    "加载中...": "Loading...",
    "处理中...": "Working...",
    "保存中...": "Saving...",
    "创建中...": "Creating...",
    "上传中...": "Uploading...",
    "删除中...": "Deleting...",
    "移除中...": "Removing...",
    "创建失败": "Create failed",
    "保存失败": "Save failed",
    "删除失败": "Delete failed",
    "上传失败": "Upload failed",
    "移除失败": "Remove failed",
    "修改失败": "Update failed",
    "语言保存失败": "Failed to save languages",
    "批量上传失败": "Batch upload failed",
    "全部文件上传失败": "All files failed to upload",
    "图标上传失败": "Icon upload failed",
    "创建组织": "Create organization",
    "创建项目": "Create project",
    "删除项目": "Delete project",
    "删除文件": "Delete file",
    "保存设置": "Save settings",
    "保存 README": "Save README",
    "组织已更新": "Organization updated",
    "项目已更新": "Project updated",
    "README 已更新": "README updated",
    "文件已删除": "File deleted",
    "角色已更新": "Role updated",
    "添加成员": "Add member",
    "添加中...": "Adding...",
    "主导航": "Main navigation",
    "切换深浅色": "Toggle light/dark",
    "切换至浅色": "Switch to light",
    "切换至暗色": "Switch to dark",
    "界面语言": "UI language",
    "产品能力": "Features",
    "翻译收集，像 Crowdin 一样协作": "Collect translations — collaborate like Crowdin",
    "了解能力": "Learn more",
    "本地开发：": "Local dev:",
    "以 dev-user 登录": "Sign in as dev-user",
    "（未配置 PassPort 时可用）": "(available when PassPort is not configured)",
    "组织与权限": "Orgs & roles",
    "所有者 / 管理员 / 译者 / 访客 四级角色，协作边界清晰。": "Owner / manager / translator / viewer roles with clear boundaries.",
    "JSON 源文件": "JSON source files",
    "支持扁平与嵌套 i18n JSON，保留结构导出，更新源文不丢已有译文。": "Flat or nested i18n JSON, structure-preserving export, keep translations when source updates.",
    "左 key 右译文，筛选未译、自动保存，进度一目了然。": "Keys on the left, translations on the right — filter untranslated, autosave, clear progress.",
    "页面不存在": "Page not found",
    "你访问的地址无效或资源已被删除。": "This address is invalid or the resource was removed.",
    "返回工作台": "Back to workspace",
    "返回项目": "Back to project",
    "暂无简介": "No description yet",
    "源语言": "Source language",
    "目标语言": "Target languages",
    "选择语言…": "Choose languages…",
    "选择目标语言": "Select target languages",
    "全部语言": "All languages",
    "已选语言": "Selected languages",
    "添加自定义语言": "Add custom language",
    "尚未选择语言": "No languages selected",
    "（自定义）": "(custom)",
    "总览": "Overview",
    "成员": "Members",
    "项目": "Projects",
    "公开": "Public",
    "私有": "Private",
    "语言": "Languages",
    "进度": "Progress",
    "批准": "Approve",
    "翻译": "Translate",
    "审核": "Proofread",
    "列表": "List",
    "辅助": "Side panel",
    "就绪": "Ready",
    "原文": "Source",
    "建议": "Suggestions",
    "语境": "Context",
    "讨论": "Discussion",
    "发送": "Send",
    "文件": "Files",
    "名称": "Name",
    "打开": "Open",
    "编辑": "Edit",
    "图标": "Icon",
    "组织": "Organization",
    "新建": "New",
    "简介": "About",
    "职责": "Role",
    "译者": "Translator",
    "审核员": "Proofreader",
    "所有者": "Owner",
    "管理员": "Manager",
    "访客": "Viewer",
    "用户": "User",
    "角色": "Role",
    "操作": "Actions",
    "内容": "Content",
    "状态": "Status",
    "待办": "To do",
    "格式": "Format",
    "详情": "Details",
    "范围": "Scope",
    "支持": "Support",
    "路径": "Path",
    "版本": "Version",
    "搜索 key 或源文": "Search key or source",
    "筛选状态": "Filter status",
    "字符串列表": "String list",
    "翻译区": "Translation area",
    "辅助信息": "Side info",
    "输入译文…": "Enter translation…",
    "上一条": "Previous",
    "下一条": "Next",
    "关闭侧栏": "Close drawer",
    "切换字符串列表": "Toggle string list",
    "切换辅助面板": "Toggle side panel",
    "工作身份": "Work mode",
    "按已有权限切换翻译 / 审核视角": "Switch translate / proofread view by your permissions",
    "翻译进度": "Translation progress",
    "绿：已批准 · 黄：有保存译文 · 灰：未翻译": "Green: approved · Yellow: has draft · Gray: untranslated",
    "当前列表 / 总数": "Visible / total",
    "用户设置 · 快捷键": "User settings · shortcuts",
    "Ctrl/⌘+Enter 保存并下一条 · Ctrl/⌘+S 仅保存": "Ctrl/⌘+Enter save & next · Ctrl/⌘+S save only",
    "在光标处插入源文": "Insert source at cursor",
    "更多操作": "More actions",
    "上一条 (↑)": "Previous (↑)",
    "下一条 (↓)": "Next (↓)",
    "说明（可选）": "Caption (optional)",
    "讨论语境、术语…": "Discuss context, terms…",
    "设置分区": "Settings sections",
    "请至少选择一种目标语言": "Select at least one target language",
    "请选择文件或粘贴内容": "Choose a file or paste content",
    "请填写项目内路径": "Enter a project-relative path",
    "上传 / 更新": "Upload / update",
    "将上传 ": "Will upload ",
    " 个文件：": " file(s):",
    "选择图片": "Choose image",
    "确定移除图标？": "Remove icon?",
    "图标已上传并保存": "Icon uploaded and saved",
    "图标已移除": "Icon removed",
    "读取文件失败": "Failed to read file",
    "缺少组织/项目上下文": "Missing org/project context",
    "图标不能超过 2MB": "Icon must be ≤ 2MB",
    "无法读取图片": "Could not read image",
    "图床未返回地址": "Image host returned no URL",
    "简体中文": "Simplified Chinese",
    "繁體中文": "Traditional Chinese",
    "英语": "English",
    "英语（美国）": "English (US)",
    "英语（英国）": "English (UK)",
    "日语": "Japanese",
    "韩语": "Korean",
    "法语": "French",
    "德语": "German",
    "西班牙语": "Spanish",
    "葡萄牙语": "Portuguese",
    "葡萄牙语（巴西）": "Portuguese (Brazil)",
    "俄语": "Russian",
    "意大利语": "Italian",
    "越南语": "Vietnamese",
    "泰语": "Thai",
    "印尼语": "Indonesian",
    "马来语": "Malay",
    "阿拉伯语": "Arabic",
    "印地语": "Hindi",
    "土耳其语": "Turkish",
    "波兰语": "Polish",
    "荷兰语": "Dutch",
    "瑞典语": "Swedish",
    "乌克兰语": "Ukrainian",
    "登录失败：": "Sign-in failed: ",
    "你取消了授权，或 PassPort 未返回授权码。": "You cancelled authorization, or PassPort did not return a code.",
    "Bloret 翻译收集平台 — 组织 · 项目 · 文件 · 语言": "Bloret Translation Collector — orgs · projects · files · languages",
    "无效目标语言": "Invalid target locale",
    "用户不存在": "User not found",
    "用户不是本组织成员": "User is not a member of this organization",
    "无效状态": "Invalid status",
    "缺少 locale": "Missing locale",
    "该源术语已存在": "This source term already exists",
    "组织 slug 已存在": "Organization slug already exists",
    "Slug 只能包含小写字母、数字与连字符": "Slug may only contain lowercase letters, digits, and hyphens",
    "无效的语言代码": "Invalid locale code",
    "缺少目标语言": "Missing target languages",
    "路径须为 .json / .properties 且仅含安全字符": "Path must be .json / .properties with safe characters only",
    "至少上传一个文件": "Upload at least one file",
    "单次最多 50 个文件": "At most 50 files per batch",
    "README URL 须为 https:// 开头的有效地址": "README URL must be a valid https:// address",
    "图标 URL 须为 https:// 开头的有效地址": "Icon URL must be a valid https:// address",
    "未解析到任何可翻译字符串": "No translatable strings found",
    "MT 返回空结果": "MT returned an empty result",
    "MT 网络错误": "MT network error",
    "请上传 data URL 格式的图片 (png/jpg/gif/webp)": "Upload a data-URL image (png/jpg/gif/webp)",
    "图片不能超过 3MB": "Image must be ≤ 3MB",
}

# merge previous non-cjk en if any
en_path = ROOT / "lang" / "en.json"
old = json.loads(en_path.read_text(encoding="utf-8")) if en_path.exists() else {}
cjk = re.compile(r"[\u4e00-\u9fff]")
en = {}
for k in zh:
    if k in HAND:
        en[k] = HAND[k]
    elif k in old and isinstance(old[k], str) and old[k] and not cjk.search(old[k]):
        en[k] = old[k]
    else:
        en[k] = k  # fallback to source; runtime still shows ZH until polished

en_path.write_text(json.dumps(en, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
mapped = sum(1 for k, v in en.items() if v != k)
print(f"en keys={len(en)} hand/mapped={mapped} identity={len(en)-mapped}")
